import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import type { PlantTemplate } from '@/types'

export const usePlantDatabaseStore = defineStore('plantDatabase', () => {
  const searchTerm = ref('')
  const filterType = ref('all')

  const plantDatabase = ref<PlantTemplate[]>([
    // Vegetables
    {
      name: 'Tomato',
      nameDutch: 'Tomaat',
      scientific: 'Solanum lycopersicum',
      emoji: '🍅',
      type: 'vegetable',
      daysToMaturity: 75,
      sunRequirement: 'full-sun',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '24 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Carrot',
      nameDutch: 'Wortel',
      scientific: 'Daucus carota',
      emoji: '🥕',
      type: 'vegetable',
      daysToMaturity: 70,
      sunRequirement: 'full-sun',
      waterFrequency: 'every-2-days',
      soilType: 'sandy',
      spacing: '2 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Lettuce',
      nameDutch: 'Sla',
      scientific: 'Lactuca sativa',
      emoji: '🥬',
      type: 'vegetable',
      daysToMaturity: 45,
      sunRequirement: 'partial-shade',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '6 inches',
      plantingDepth: '1/8 inch',
    },
    {
      name: 'Bell Pepper',
      nameDutch: 'Paprika',
      scientific: 'Capsicum annuum',
      emoji: '🫑',
      type: 'vegetable',
      daysToMaturity: 80,
      sunRequirement: 'full-sun',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '18 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Cucumber',
      nameDutch: 'Komkommer',
      scientific: 'Cucumis sativus',
      emoji: '🥒',
      type: 'vegetable',
      daysToMaturity: 60,
      sunRequirement: 'full-sun',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '36 inches',
      plantingDepth: '1/2 inch',
    },
    {
      name: 'Broccoli',
      nameDutch: 'Broccoli',
      scientific: 'Brassica oleracea',
      emoji: '🥦',
      type: 'vegetable',
      daysToMaturity: 85,
      sunRequirement: 'full-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '18 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Spinach',
      nameDutch: 'Spinazie',
      scientific: 'Spinacia oleracea',
      emoji: '🍃',
      type: 'vegetable',
      daysToMaturity: 40,
      sunRequirement: 'partial-shade',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '4 inches',
      plantingDepth: '1/2 inch',
    },
    {
      name: 'Radish',
      nameDutch: 'Radijs',
      scientific: 'Raphanus sativus',
      emoji: '🔴',
      type: 'vegetable',
      daysToMaturity: 25,
      sunRequirement: 'full-sun',
      waterFrequency: 'daily',
      soilType: 'sandy',
      spacing: '2 inches',
      plantingDepth: '1/2 inch',
    },
    {
      name: 'Onion',
      nameDutch: 'Ui',
      scientific: 'Allium cepa',
      emoji: '🧅',
      type: 'vegetable',
      daysToMaturity: 120,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'loamy',
      spacing: '4 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Garlic',
      nameDutch: 'Knoflook',
      scientific: 'Allium sativum',
      emoji: '🧄',
      type: 'vegetable',
      daysToMaturity: 240,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'loamy',
      spacing: '6 inches',
      plantingDepth: '2 inches',
    },
    {
      name: 'Kale',
      nameDutch: 'Boerenkool',
      scientific: 'Brassica oleracea',
      emoji: '🥬',
      type: 'vegetable',
      daysToMaturity: 55,
      sunRequirement: 'partial-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '12 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Zucchini',
      nameDutch: 'Courgette',
      scientific: 'Cucurbita pepo',
      emoji: '🥒',
      type: 'vegetable',
      daysToMaturity: 50,
      sunRequirement: 'full-sun',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '36 inches',
      plantingDepth: '1 inch',
    },
    {
      name: 'Eggplant',
      nameDutch: 'Aubergine',
      scientific: 'Solanum melongena',
      emoji: '🍆',
      type: 'vegetable',
      daysToMaturity: 85,
      sunRequirement: 'full-sun',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '24 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Green Beans',
      nameDutch: 'Sperziebonen',
      scientific: 'Phaseolus vulgaris',
      emoji: '🫘',
      type: 'vegetable',
      daysToMaturity: 55,
      sunRequirement: 'full-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '6 inches',
      plantingDepth: '1 inch',
    },
    {
      name: 'Peas',
      nameDutch: 'Erwten',
      scientific: 'Pisum sativum',
      emoji: '🟢',
      type: 'vegetable',
      daysToMaturity: 65,
      sunRequirement: 'partial-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '4 inches',
      plantingDepth: '1 inch',
    },
    {
      name: 'Cabbage',
      nameDutch: 'Kool',
      scientific: 'Brassica oleracea',
      emoji: '🥬',
      type: 'vegetable',
      daysToMaturity: 90,
      sunRequirement: 'full-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '18 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Cauliflower',
      nameDutch: 'Bloemkool',
      scientific: 'Brassica oleracea',
      emoji: '🥦',
      type: 'vegetable',
      daysToMaturity: 95,
      sunRequirement: 'full-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '18 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Leek',
      nameDutch: 'Prei',
      scientific: 'Allium porrum',
      emoji: '🥬',
      type: 'vegetable',
      daysToMaturity: 120,
      sunRequirement: 'full-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '6 inches',
      plantingDepth: '1/2 inch',
    },
    {
      name: 'Brussels Sprouts',
      nameDutch: 'Spruitjes',
      scientific: 'Brassica oleracea',
      emoji: '🥬',
      type: 'vegetable',
      daysToMaturity: 110,
      sunRequirement: 'full-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '18 inches',
      plantingDepth: '1/4 inch',
    },

    // Fruits
    {
      name: 'Strawberry',
      nameDutch: 'Aardbei',
      scientific: 'Fragaria × ananassa',
      emoji: '🍓',
      type: 'fruit',
      daysToMaturity: 90,
      sunRequirement: 'full-sun',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '12 inches',
      plantingDepth: 'surface',
    },
    {
      name: 'Blueberry',
      nameDutch: 'Bosbes',
      scientific: 'Vaccinium corymbosum',
      emoji: '🫐',
      type: 'fruit',
      daysToMaturity: 365,
      sunRequirement: 'full-sun',
      waterFrequency: 'twice-weekly',
      soilType: 'peaty',
      spacing: '48 inches',
      plantingDepth: 'root level',
    },
    {
      name: 'Raspberry',
      nameDutch: 'Framboos',
      scientific: 'Rubus idaeus',
      emoji: '🍇',
      type: 'fruit',
      daysToMaturity: 365,
      sunRequirement: 'partial-sun',
      waterFrequency: 'twice-weekly',
      soilType: 'loamy',
      spacing: '24 inches',
      plantingDepth: 'root level',
    },
    {
      name: 'Blackberry',
      nameDutch: 'Braam',
      scientific: 'Rubus fruticosus',
      emoji: '🫐',
      type: 'fruit',
      daysToMaturity: 365,
      sunRequirement: 'partial-sun',
      waterFrequency: 'twice-weekly',
      soilType: 'loamy',
      spacing: '36 inches',
      plantingDepth: 'root level',
    },
    {
      name: 'Watermelon',
      nameDutch: 'Watermeloen',
      scientific: 'Citrullus lanatus',
      emoji: '🍉',
      type: 'fruit',
      daysToMaturity: 90,
      sunRequirement: 'full-sun',
      waterFrequency: 'daily',
      soilType: 'sandy',
      spacing: '72 inches',
      plantingDepth: '1 inch',
    },
    {
      name: 'Cantaloupe',
      nameDutch: 'Meloen',
      scientific: 'Cucumis melo',
      emoji: '🍈',
      type: 'fruit',
      daysToMaturity: 85,
      sunRequirement: 'full-sun',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '36 inches',
      plantingDepth: '1/2 inch',
    },
    {
      name: 'Apple Tree',
      nameDutch: 'Appelboom',
      scientific: 'Malus domestica',
      emoji: '🍎',
      type: 'fruit',
      daysToMaturity: 1095,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'loamy',
      spacing: '180 inches',
      plantingDepth: 'root level',
    },
    {
      name: 'Pear Tree',
      nameDutch: 'Perenboom',
      scientific: 'Pyrus communis',
      emoji: '🍐',
      type: 'fruit',
      daysToMaturity: 1095,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'loamy',
      spacing: '180 inches',
      plantingDepth: 'root level',
    },
    {
      name: 'Cherry Tree',
      nameDutch: 'Kersenboom',
      scientific: 'Prunus avium',
      emoji: '🍒',
      type: 'fruit',
      daysToMaturity: 1095,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'loamy',
      spacing: '240 inches',
      plantingDepth: 'root level',
    },
    {
      name: 'Grape Vine',
      nameDutch: 'Druivenrank',
      scientific: 'Vitis vinifera',
      emoji: '🍇',
      type: 'fruit',
      daysToMaturity: 730,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'loamy',
      spacing: '72 inches',
      plantingDepth: 'root level',
    },

    // Herbs
    {
      name: 'Basil',
      nameDutch: 'Basilicum',
      scientific: 'Ocimum basilicum',
      emoji: '🌿',
      type: 'herb',
      daysToMaturity: 60,
      sunRequirement: 'full-sun',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '12 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Rosemary',
      nameDutch: 'Rozemarijn',
      scientific: 'Rosmarinus officinalis',
      emoji: '🌿',
      type: 'herb',
      daysToMaturity: 90,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'sandy',
      spacing: '24 inches',
      plantingDepth: 'surface',
    },
    {
      name: 'Thyme',
      nameDutch: 'Tijm',
      scientific: 'Thymus vulgaris',
      emoji: '🌿',
      type: 'herb',
      daysToMaturity: 75,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'sandy',
      spacing: '8 inches',
      plantingDepth: 'surface',
    },
    {
      name: 'Oregano',
      nameDutch: 'Oregano',
      scientific: 'Origanum vulgare',
      emoji: '🌿',
      type: 'herb',
      daysToMaturity: 80,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'loamy',
      spacing: '10 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Parsley',
      nameDutch: 'Peterselie',
      scientific: 'Petroselinum crispum',
      emoji: '🌿',
      type: 'herb',
      daysToMaturity: 70,
      sunRequirement: 'partial-shade',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '6 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Cilantro',
      nameDutch: 'Koriander',
      scientific: 'Coriandrum sativum',
      emoji: '🌿',
      type: 'herb',
      daysToMaturity: 45,
      sunRequirement: 'partial-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '4 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Mint',
      nameDutch: 'Munt',
      scientific: 'Mentha',
      emoji: '🌿',
      type: 'herb',
      daysToMaturity: 60,
      sunRequirement: 'partial-shade',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '12 inches',
      plantingDepth: 'surface',
    },
    {
      name: 'Sage',
      nameDutch: 'Salie',
      scientific: 'Salvia officinalis',
      emoji: '🌿',
      type: 'herb',
      daysToMaturity: 75,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'sandy',
      spacing: '18 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Chives',
      nameDutch: 'Bieslook',
      scientific: 'Allium schoenoprasum',
      emoji: '🌿',
      type: 'herb',
      daysToMaturity: 60,
      sunRequirement: 'partial-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '6 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Dill',
      nameDutch: 'Dille',
      scientific: 'Anethum graveolens',
      emoji: '🌿',
      type: 'herb',
      daysToMaturity: 65,
      sunRequirement: 'full-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '8 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Fennel',
      nameDutch: 'Venkel',
      scientific: 'Foeniculum vulgare',
      emoji: '🌿',
      type: 'herb',
      daysToMaturity: 85,
      sunRequirement: 'full-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '12 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Tarragon',
      nameDutch: 'Dragon',
      scientific: 'Artemisia dracunculus',
      emoji: '🌿',
      type: 'herb',
      daysToMaturity: 90,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'loamy',
      spacing: '18 inches',
      plantingDepth: 'surface',
    },

    // Flowers
    {
      name: 'Marigold',
      nameDutch: 'Goudsbloem',
      scientific: 'Tagetes',
      emoji: '🌼',
      type: 'flower',
      daysToMaturity: 50,
      sunRequirement: 'full-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '8 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Sunflower',
      nameDutch: 'Zonnebloem',
      scientific: 'Helianthus annuus',
      emoji: '🌻',
      type: 'flower',
      daysToMaturity: 80,
      sunRequirement: 'full-sun',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '24 inches',
      plantingDepth: '1/2 inch',
    },
    {
      name: 'Zinnia',
      nameDutch: 'Zinnia',
      scientific: 'Zinnia elegans',
      emoji: '🌸',
      type: 'flower',
      daysToMaturity: 60,
      sunRequirement: 'full-sun',
      waterFrequency: 'every-2-days',
      soilType: 'loamy',
      spacing: '12 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Nasturtium',
      nameDutch: 'Oost-Indische kers',
      scientific: 'Tropaeolum majus',
      emoji: '🌺',
      type: 'flower',
      daysToMaturity: 55,
      sunRequirement: 'partial-sun',
      waterFrequency: 'every-2-days',
      soilType: 'sandy',
      spacing: '10 inches',
      plantingDepth: '1/2 inch',
    },
    {
      name: 'Cosmos',
      nameDutch: 'Cosmos',
      scientific: 'Cosmos bipinnatus',
      emoji: '🌸',
      type: 'flower',
      daysToMaturity: 70,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'sandy',
      spacing: '12 inches',
      plantingDepth: '1/4 inch',
    },
    {
      name: 'Lavender',
      nameDutch: 'Lavendel',
      scientific: 'Lavandula',
      emoji: '💜',
      type: 'flower',
      daysToMaturity: 90,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'sandy',
      spacing: '18 inches',
      plantingDepth: 'surface',
    },
    {
      name: 'Petunia',
      nameDutch: 'Petunia',
      scientific: 'Petunia × atkinsiana',
      emoji: '🌺',
      type: 'flower',
      daysToMaturity: 65,
      sunRequirement: 'full-sun',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '8 inches',
      plantingDepth: 'surface',
    },
    {
      name: 'Impatiens',
      nameDutch: 'Vlijtig liesje',
      scientific: 'Impatiens walleriana',
      emoji: '🌸',
      type: 'flower',
      daysToMaturity: 70,
      sunRequirement: 'partial-shade',
      waterFrequency: 'daily',
      soilType: 'loamy',
      spacing: '8 inches',
      plantingDepth: 'surface',
    },
    {
      name: 'Tulip',
      nameDutch: 'Tulp',
      scientific: 'Tulipa',
      emoji: '🌷',
      type: 'flower',
      daysToMaturity: 180,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'loamy',
      spacing: '6 inches',
      plantingDepth: '6 inches',
    },
    {
      name: 'Daffodil',
      nameDutch: 'Narcis',
      scientific: 'Narcissus',
      emoji: '🌼',
      type: 'flower',
      daysToMaturity: 180,
      sunRequirement: 'partial-sun',
      waterFrequency: 'weekly',
      soilType: 'loamy',
      spacing: '6 inches',
      plantingDepth: '6 inches',
    },
    {
      name: 'Hyacinth',
      nameDutch: 'Hyacint',
      scientific: 'Hyacinthus',
      emoji: '🌸',
      type: 'flower',
      daysToMaturity: 180,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'loamy',
      spacing: '6 inches',
      plantingDepth: '6 inches',
    },
    {
      name: 'Crocus',
      nameDutch: 'Krokus',
      scientific: 'Crocus',
      emoji: '🌼',
      type: 'flower',
      daysToMaturity: 120,
      sunRequirement: 'full-sun',
      waterFrequency: 'weekly',
      soilType: 'loamy',
      spacing: '3 inches',
      plantingDepth: '3 inches',
    },
  ])

  const filteredDatabase = computed(() => {
    let result = plantDatabase.value

    if (filterType.value !== 'all') {
      result = result.filter((p) => p.type === filterType.value)
    }

    if (searchTerm.value) {
      const term = searchTerm.value.toLowerCase()
      result = result.filter(
        (p) =>
          p.name.toLowerCase().includes(term) ||
          p.nameDutch.toLowerCase().includes(term) ||
          p.scientific.toLowerCase().includes(term),
      )
    }

    return result
  })

  const vegetables = computed(() => plantDatabase.value.filter((p) => p.type === 'vegetable'))
  const fruits = computed(() => plantDatabase.value.filter((p) => p.type === 'fruit'))
  const herbs = computed(() => plantDatabase.value.filter((p) => p.type === 'herb'))
  const flowers = computed(() => plantDatabase.value.filter((p) => p.type === 'flower'))

  function setSearchTerm(term: string) {
    searchTerm.value = term
  }

  function setFilterType(type: string) {
    filterType.value = type
  }

  return {
    plantDatabase,
    searchTerm,
    filterType,
    filteredDatabase,
    vegetables,
    fruits,
    herbs,
    flowers,
    setSearchTerm,
    setFilterType,
  }
})
